### ISSUE TITLE
Genserver使用不当

### ISSUE THREAD

**Issue by bigfang** [bigfang/crawl-exercise#1]
Crawlex.Worker.run 偶数次运行时会挂
```
iex(2)> Crawlex.Worker.run
23:00:41.351 [info] Crawler is Starting!
** (exit) exited in: GenServer.call(Crawlex.Worker, :run, 5000)
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {:already_started, #PID<0.239.0>}}
            (crawlex) lib/crawlex/fetcher.ex:14: Crawlex.Fetcher.start_link/0
            (crawlex) lib/crawlex/worker.ex:40: Crawlex.Worker.work/0
            (crawlex) lib/crawlex/worker.ex:55: Crawlex.Worker.handle_call/3
            (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
23:00:41.386 [error] GenServer Crawlex.Worker terminating
** (MatchError) no match of right hand side value: {:error, {:already_started, #PID<0.239.0>}}
    (crawlex) lib/crawlex/fetcher.ex:14: Crawlex.Fetcher.start_link/0
    (crawlex) lib/crawlex/worker.ex:40: Crawlex.Worker.work/0
    (crawlex) lib/crawlex/worker.ex:55: Crawlex.Worker.handle_call/3
    (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :run
State: nil
    (elixir) lib/gen_server.ex:737: GenServer.call/3
```

**Comment by bigfang** [comment]
似乎 3201668c4169b3c41bff821c236ba42584681a54 修复了该问题

**Comment by bigfang** [comment]
似乎 3201668c4169b3c41bff821c236ba42584681a54 修复了该问题
